# Generated by Django 5.1 on 2024-09-23 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_restaurants_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurants',
            old_name='city',
            new_name='location',
        ),
    ]
