# Generated by Django 5.1 on 2026-06-18 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_seed_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
