# Generated by Django 5.1 on 2026-06-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
